### ISSUE TITLE
You probably meant something else here...

### ISSUE THREAD

**Issue by ttsiodras** [mmmonk/crap#2]
In this part of your code...

https://github.com/mmmonk/crap/blob/a1a7cfb45fe426c7e9e53f42f6d964a8048adde2/tcp_and_proxy/nagle.c#L31

...I am pretty sure you meant something else - e.g.

    char buff[BUFFSIZE];

...or even better,

    static char buff[BUFFSIZE];

Right?

**Comment by mmmonk** [comment]
yeah, right, took me a while to look here ;)
thanks, fixed
